server:
  port: 8762
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 
    register-with-eureka: false
spring:
  application:
    name: gateway-service
  



management.endpoints.web.exposure.include: '*'