version: "3.9"
services:
 discovery:
   build: ../discovery-server
   ports:
     - "8761:8761"
   image: "discovery-service"
 hotel_A:
   build: ../Hotel
   environment:
     - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
   ports:
     - "3000:8080"
   image: "hotel-service"
   depends_on:
     - discovery
    
 ReservationA:
   build: ../ReservationVol-Service
   environment:
    - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
   ports:
   - "3001:8081"
   image: "docker-service-reservationvol"
   depends_on:
     - discovery
  
  
 ReservationB:
   build: ../ReservationVol-Service
   environment:
    - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
   ports:
    - "3002:8081"
   image: "docker-service-reservationvol"
   depends_on:
      - discovery
   
   
 Gateway:
   build: ../gateway-server
   environment:
    - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
   ports:
    - "8762:8762"
   image: "docker-gateway"
   depends_on:
      - discovery
   
  
 voiture:
   build: ../LocationVoiture
   environment:
    - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
   ports:
    - "3006:8082"
   image: "docker-locationvoiture"
   depends_on:
      - discovery  
  
  
  
 Bateau:
   build: ../bateau
   ports:
    - "3005:3005"
   image: "docker-bateau-node"
   links:
    - mongo
   depends_on:
     - discovery
      
      
 mongo:
   container_name: mongo
   ports:
    - "27017:27017"
   image: "mongo"
   